name: Update
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

permissions: 
  pull-requests: write
  
jobs:
  flutter:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update Flutter version
        id: update
        run: ./update/update.py >> "$GITHUB_OUTPUT"
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          commit-msg: |
            update Flutter to ${{steps.update.outputs.flutterVersion}} and flake.lock

            Flutter: ${{steps.update.outputs.flutterVersion}}
            Dart: ${{steps.update.outputs.dartVersion}}
            Engine: ${{steps.update.outputs.engine}}
          pr-assignees: maximoffua
          pr-reviewers: maximoffua
          pr-title: "Update Flutter" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated

